Revert "change to git workflows"
This reverts commit 03c68f7343b98c85d64e7904e6e4d32dd20dfb04.

diff --git a/.github/actions/install_requirements/action.yml b/.github/actions/install_requirements/action.yml
--- a/.github/actions/install_requirements/action.yml
+++ b/.github/actions/install_requirements/action.yml
@@ -1,34 +1,60 @@
 name: Install requirements
-description: Install a version of python then call pip install and report what was installed
+description: Run pip install with requirements and upload resulting requirements
 inputs:
-  python-version:
-    description: Python version to install, default is from Dockerfile
-    default: "dev"
-  pip-install:
+  requirements_file:
+    description: Name of requirements file to use and upload
+    required: true
+  install_options:
     description: Parameters to pass to pip install
-    default: "$([ -f dev-requirements.txt ] && echo '-c dev-requirements.txt') -e .[dev]"
+    required: true
+  artifact_name:
+    description: A user friendly name to give the produced artifacts
+    required: true
+  python_version:
+    description: Python version to install
+    default: "3.11"
 
 runs:
   using: composite
-  steps:
-    - name: Get version of python
-      run: |
-        PYTHON_VERSION="${{ inputs.python-version }}"
-        if [ $PYTHON_VERSION == "dev" ]; then
-          PYTHON_VERSION=$(sed -n "s/ARG PYTHON_VERSION=//p" Dockerfile)
-        fi
-        echo "PYTHON_VERSION=$PYTHON_VERSION" >> "$GITHUB_ENV"
-      shell: bash
 
+  steps:
     - name: Setup python
       uses: actions/setup-python@v5
       with:
-        python-version: ${{ env.PYTHON_VERSION }}
+        python-version: ${{ inputs.python_version }}
 
-    - name: Install packages
-      run: pip install ${{ inputs.pip-install }}
+    - name: Pip install
+      run: |
+        touch ${{ inputs.requirements_file }}
+        # -c uses requirements.txt as constraints, see 'Validate requirements file'
+        pip install -c ${{ inputs.requirements_file }} ${{ inputs.install_options }}
       shell: bash
 
-    - name: Report what was installed
-      run: pip freeze
+    - name: Create lockfile
+      run: |
+        mkdir -p lockfiles
+        pip freeze --exclude-editable > lockfiles/${{ inputs.requirements_file }}
+        # delete the self referencing line and make sure it isn't blank
+        sed -i'' -e '/file:/d' lockfiles/${{ inputs.requirements_file }}
+      shell: bash
+
+    - name: Upload lockfiles
+      uses: actions/upload-artifact@v4.0.0
+      with:
+        name: lockfiles-${{ inputs.python_version }}-${{ inputs.artifact_name }}-${{ github.sha }}
+        path: lockfiles
+
+    # This eliminates the class of problems where the requirements being given no
+    # longer match what the packages themselves dictate. E.g. In the rare instance
+    # where I install some-package which used to depend on vulnerable-dependency
+    # but now uses good-dependency (despite being nominally the same version)
+    # pip will install both if given a requirements file with -r
+    - name: If requirements file exists, check it matches pip installed packages
+      run: |
+        if [ -s ${{ inputs.requirements_file }} ]; then
+          if ! diff -u ${{ inputs.requirements_file }} lockfiles/${{ inputs.requirements_file }}; then
+            echo "Error: ${{ inputs.requirements_file }} need the above changes to be exhaustive"
+            exit 1
+          fi
+        fi
       shell: bash
